# Generated by Django 3.2.15 on 2022-08-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LineGraph_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineG',
        ),
    ]
